[versions]
compileSdk = "<%= androidTargetSdkVersion %>"
buildTools = "30.0.3"
minSdk = "<%= androidMinSdkVersion %>"
targetSdk = "<%= androidTargetSdkVersion %>"
appVersionCode = "1"
appVersionName = "1.0"
